name: build-signpath

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+.[0-9]+

env:
  BUILD_VERSION: ${{ github.ref_name }}

jobs:
  rainmeter:
    strategy:
      matrix:
        arch: [32, 64]

    runs-on: windows-2025-vs2026
    steps:
      - name: Clone repo
        uses: actions/checkout@v5

      - name: Build ${{ matrix.arch }}-bit Rainmeter
        run: |
          $buildVersion = $env:BUILD_VERSION.Substring(1)
          .\Build\Build.ps1 rainmeter-${{ matrix.arch }} $buildVersion
        shell: pwsh

      - name: Upload ${{ matrix.arch }}-bit build
        uses: actions/upload-artifact@v7
        with:
          name: BuildOut-${{ matrix.arch }}
          path: |
            BuildOut
            !BuildOut/*/Obj
          if-no-files-found: error

  installer:
    environment:
      name: signpath
      deployment: false
    needs: rainmeter
    runs-on: windows-2025-vs2026
    steps:
      - name: Clone repo
        uses: actions/checkout@v5

      - name: Download 32-bit & 64-bit builds
        uses: actions/download-artifact@v8
        with:
          pattern: BuildOut-*
          path: BuildOut

      - name: Upload combined build
        uses: actions/upload-artifact@v7
        id: upload-build
        with:
          name: RainmeterBuild-${{ github.ref_name }}
          path: BuildOut
          if-no-files-found: error

      - name: Remove build directories
        run: rm -rf BuildOut
        shell: bash

      - name: Sign Rainmeter
        uses: signpath/github-action-submit-signing-request@b9d91eadd323de506c0c81cf0c7fe7438f3360fd # v2.2
        with:
          api-token: '${{ secrets.SIGNPATH_API_KEY }}'
          organization-id: '2d37d539-98b7-4649-9469-4097b1099202'
          project-slug: 'rainmeter'
          signing-policy-slug: 'release-signing'
          artifact-configuration-slug: 'zip'
          github-artifact-id: '${{ steps.upload-build.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: .

      - name: Install NSIS
        uses: ./.github/actions/install-nsis

      - name: Build installer
        run: |
          $buildVersion = $env:BUILD_VERSION.Substring(1)
          .\Build\Build.ps1 installer $buildVersion
        shell: pwsh

      - name: Upload installer
        uses: actions/upload-artifact@v7
        id: upload-installer
        with:
          path: Build/Rainmeter-*.exe
          archive: false
          if-no-files-found: error

      - name: Sign installer
        uses: signpath/github-action-submit-signing-request@b9d91eadd323de506c0c81cf0c7fe7438f3360fd # v2.2
        with:
          api-token: '${{ secrets.SIGNPATH_API_KEY }}'
          organization-id: '2d37d539-98b7-4649-9469-4097b1099202'
          project-slug: 'rainmeter'
          signing-policy-slug: 'release-signing'
          artifact-configuration-slug: 'exe'
          github-artifact-id: '${{ steps.upload-installer.outputs.artifact-id }}'
          wait-for-completion: false
