name: build-signpath

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    environment: signpath
    runs-on: windows-2025
    steps:
      - name: Install NSIS
        run: choco install nsis --version=3.10.0 --no-progress

      - name: Clone repo
        uses: actions/checkout@v5

      - name: Build Rainmeter
        run: cd Build && Build.bat release %GITHUB_REF_NAME:~1%
        shell: cmd

      - name: Remove object directories
        run: rm -rf {x32,x64}-Release/Obj
        shell: bash

      - name: Upload build
        uses: actions/upload-artifact@v7
        id: upload-build
        with:
          name: RainmeterBuild-${{ github.ref_name }}
          path: |
            x32-Release
            x64-Release
          if-no-files-found: error

      - name: Remove build directories
        run: rm -rf {x32,x64}-Release
        shell: bash

      - name: Sign Rainmeter
        uses: signpath/github-action-submit-signing-request@b9d91eadd323de506c0c81cf0c7fe7438f3360fd # v2.2
        with:
          api-token: '${{ secrets.SIGNPATH_API_KEY }}'
          organization-id: '2d37d539-98b7-4649-9469-4097b1099202'
          project-slug: 'rainmeter'
          signing-policy-slug: 'release-signing'
          github-artifact-id: '${{ steps.upload-build.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: .

      - name: Build installer
        run: cd Build && Build.bat installer %GITHUB_REF_NAME:~1%
        shell: cmd

      - name: Upload installer
        uses: actions/upload-artifact@v7
        id: upload-installer
        with:
          name: RainmeterInstaller-${{ github.ref_name }}
          path: Build/Rainmeter-*.exe
          if-no-files-found: error

      - name: Sign installer
        uses: signpath/github-action-submit-signing-request@b9d91eadd323de506c0c81cf0c7fe7438f3360fd # v2.2
        with:
          api-token: '${{ secrets.SIGNPATH_API_KEY }}'
          organization-id: '2d37d539-98b7-4649-9469-4097b1099202'
          project-slug: 'rainmeter'
          signing-policy-slug: 'release-signing'
          github-artifact-id: '${{ steps.upload-installer.outputs.artifact-id }}'
          wait-for-completion: false
