name: build-pluginapi

on:
  push:
    branches:
      - '**'
    paths:
      - 'PluginAPI/**'
      - 'Library/Exports.def'
      - 'Library/RainmeterAPI.*'
      - '.github/workflows/*pluginapi*'

jobs:
  pluginapi:
    if: "!contains(github.event.head_commit.message, 'skipci') && !contains(github.event.head_commit.message, 'ciskip')"
    runs-on: windows-2025-vs2026
    steps:
      - name: Clone repo
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          persist-credentials: false

      - name: Build plugin API
        run: .\Build\Build.ps1 plugin-api
        shell: pwsh

      - name: Upload plugin API
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: PluginAPI
          path: BuildOut/PluginAPI
          if-no-files-found: error
