name: build

on:
  push:
    branches:
      - '**'

jobs:
  rainmeter:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    strategy:
      matrix:
        arch: [32, 64]
    runs-on: windows-2022
    steps:
      - name: Clone repo
        uses: actions/checkout@v5

      - name: Build ${{ matrix.arch }}-bit Rainmeter
        run: |
          $buildVersion = "$(Get-Date -Format 'yyyy.M.d').$env:GITHUB_RUN_NUMBER"
          cd Build
          .\Build.bat rainmeter-${{ matrix.arch }} $buildVersion include-tests
        shell: pwsh

      - name: Test 64-bit Rainmeter
        if: ${{ matrix.arch == 64 }}
        run: |
          cd Build
          .\Build.bat test-64
        shell: pwsh

      - name: Upload ${{ matrix.arch }}-bit build
        uses: actions/upload-artifact@v7
        with:
          name: x${{ matrix.arch }}-Release
          path: |
            x${{ matrix.arch }}-Release
            !x${{ matrix.arch }}-Release/Obj
          if-no-files-found: error

  installer:
    needs: rainmeter
    runs-on: windows-2022
    steps:
      - name: Clone repo
        uses: actions/checkout@v5

      - name: Download 32-bit & 64-bit builds
        uses: actions/download-artifact@v8
        with:
          pattern: x*-Release

      - name: Install NSIS
        run: choco install nsis --version=3.12.0 --no-progress

      - name: Build installer
        run: |
          $buildVersion = "$(Get-Date -Format 'yyyy.M.d').$env:GITHUB_RUN_NUMBER"
          cd Build
          .\Build.bat installer $buildVersion
        shell: pwsh

      - name: Upload installer
        uses: actions/upload-artifact@v7
        id: upload-installer
        with:
          path: Build/Rainmeter-*.exe
          archive: false
          if-no-files-found: error
