name: build-nsis-plugins-signpath

on:
  workflow_dispatch:

jobs:
  build:
    environment:
      name: signpath
      deployment: false
    runs-on: windows-2025-vs2026
    steps:
      - name: Clone repo
        uses: actions/checkout@v5

      - name: Build NSIS plugins
        run: .\Build\BuildInstallerPlugins.ps1
        shell: pwsh

      - name: Upload NSIS plugins
        uses: actions/upload-artifact@v7
        id: upload-plugins
        with:
          name: NSISPlugins-unsigned
          path: BuildOut/Installer/Plugins/x86-unicode/*.dll
          if-no-files-found: error

      - name: Sign NSIS plugins
        uses: signpath/github-action-submit-signing-request@b9d91eadd323de506c0c81cf0c7fe7438f3360fd # v2.2
        with:
          api-token: '${{ secrets.SIGNPATH_API_KEY }}'
          organization-id: '2d37d539-98b7-4649-9469-4097b1099202'
          project-slug: 'rainmeter'
          signing-policy-slug: 'release-signing'
          artifact-configuration-slug: 'zip'
          github-artifact-id: '${{ steps.upload-plugins.outputs.artifact-id }}'
          wait-for-completion: false
