name: winget-manual-publish

on:
  workflow_dispatch:
    inputs:
      release-tag:
        type: string
        description: Github release tag (vX.X.X.X)
        required: true
      version:
        type: string
        description: Rainmeter version (X.X.X)
        required: true

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@a8fff44b123f115ce4c21543edf8b677376fc7e0 # main
        with:
          identifier: Rainmeter.Rainmeter
          version: ${{ inputs.version }}
          release-notes-url: https://docs.rainmeter.net/history/
          installers-regex: '\.exe$' # Only .exe files
          release-tag: ${{ inputs.release-tag }}
          token: ${{ secrets.WINGET_TOKEN }}
          fork-user: brianferguson
