name: winget-publish

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Mandatory to use the extract version from tag action

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.3.0

      - name: Verify version information
        if: ${{ env.MAJOR == '' || env.MINOR == '' || env.PATCH == '' }}
        run: |
          echo 'ERROR: Invalid version: ${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}'
          exit 1

      - name: Publish to WinGet
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Rainmeter.Rainmeter
          version: ${{ env.MAJOR}}.${{ env.MINOR }}.${{ env.PATCH }}
          release-notes-url: https://docs.rainmeter.net/history/
          installers-regex: '\.exe$' # Only .exe files
          token: ${{ secrets.WINGET_TOKEN }}
          fork-user: brianferguson
